# -*- coding: utf-8 -*-
"""「期末baseball!!」_自己try

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwcafHnSLcUwH1n94t89fDzZtk5Tr1wt

# 環境設定
"""

import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
import os

import plotly.express as px
import plotly.graph_objects as go

import joblib
from scipy import stats
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import VotingRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

from catboost import CatBoostRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

from google import genai
from google.colab import files, userdata
from pyngrok import ngrok

"""# streamlit"""

os.makedirs("shared", exist_ok=True)
os.makedirs("pages", exist_ok=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile shared/__init__.py

os.makedirs('.streamlit', exist_ok=True)

with open('.streamlit/config.toml', 'w') as f:
    f.write("""
[theme]
primaryColor = "#E31837"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#001844"
textColor = "#333333"
font = "sans serif"
""")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile shared/resources.py
# import streamlit as st
# import joblib
# import pandas as pd
# import numpy as np
# import os
# 
# MODEL_URL = "https://raw.githubusercontent.com/ChewyChloe/cpbl-project/main/cpbl_ai_model.pkl"
# DATA_URL = "https://raw.githubusercontent.com/ChewyChloe/cpbl-project/cb8796cfbf8aa99126c7aeb3044f80569b1b5ff5/team_stats_recent.csv"
# 
# @st.cache_resource
# def load_resources():
#     if not os.path.exists("cpbl_ai_model.pkl"):
#         os.system(f"wget -q -O cpbl_ai_model.pkl {MODEL_URL}")
# 
#     try:
#         model = joblib.load("cpbl_ai_model.pkl")
#     except Exception:
#         model = None
# 
#     if not os.path.exists("team_stats_recent.csv"):
#         os.system(f"wget -q -O team_stats_recent.csv {DATA_URL}")
# 
#     try:
#         df = pd.read_csv("team_stats_recent.csv")
#     except Exception:
#         df = None
# 
#     return model, df
# 
# 
# def calculate_pythagorean_win_rate(runs_scored, runs_allowed):
#     exponent = 1.83
#     if (runs_scored + runs_allowed) == 0:
#         return 0.5
#     return (runs_scored ** exponent) / ((runs_scored ** exponent) + (runs_allowed ** exponent))

"""### CSS"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile shared/styles.py
# import streamlit as st
# 
# custom_css = """
# <style>
# /* 全局 */
# .stApp { background-color: #F8F9FA; }
# 
# /* 側欄 */
# section[data-testid="stSidebar"] {
#     background-color: #001844 !important;
# }
# section[data-testid="stSidebar"] * {
#     color: #FFFFFF !important;
# }
# 
# /* 下拉選單 */
# div[data-baseweb="select"] > div,
# input[type="number"]{
#   color:white !important;
#   background-color:#002D62 !important;
#   border-radius:5px;
# }
# ul[data-baseweb="menu"] li{
#   color:black !important;
# }
# 
# .stSelectbox label, .stNumberInput label, .stSlider label{
#   color:#333333 !important;
#   font-weight:bold;
# }
# 
# /* 隱藏原生元件 */
# #MainMenu {visibility:hidden;}
# footer {visibility:hidden;}
# 
# /* 團隊卡與 Podcast 卡 */
# .podcast-card{
#   background-color:#FFFFFF;
#   border-radius:12px;
#   box-shadow:0 4px 12px rgba(0,0,0,0.08);
#   padding:15px;
#   margin-bottom:20px;
#   border:1px solid #e0e0e0;
#   transition:transform 0.2s, box-shadow 0.2s;
#   display:flex;
#   flex-direction:column;
#   align-items:center;
#   text-align:center;
# }
# .podcast-card:hover{
#   transform:translateY(-5px);
#   box-shadow:0 8px 20px rgba(0,0,0,0.15);
# }
# .podcast-card h3{
#   color:#001844;
#   font-size:18px;
#   font-weight:700;
#   margin-top:15px;
#   margin-bottom:5px;
#   text-align:center;
# }
# .video-container{
#   position:relative;
#   width:100%;
#   padding-bottom:56.25%;
#   height:0;
#   overflow:hidden;
#   border-radius:8px;
# }
# .video-container iframe{
#   position:absolute;
#   top:0; left:0;
#   width:100%;
#   height:100%;
#   border:0;
# }
# 
# /* 開發團隊 */
# .team-card{
#   background-color:#FFF5F7;
#   border:2px solid #FFD1DC;
#   border-radius:20px;
#   padding:20px;
#   text-align:center;
#   margin-bottom:20px;
#   box-shadow:0 4px 10px rgba(255,182,193,0.2);
#   transition:transform 0.3s ease;
#   height: 100%;
# }
# .team-card:hover{
#   transform:translateY(-5px);
#   box-shadow:0 8px 15px rgba(255,182,193,0.5);
# }
# .team-name{
#   color:#001844;
#   font-size:20px;
#   font-weight:bold;
#   margin-bottom:5px;
# }
# .team-info{
#   color:#666;
#   font-size:14px;
#   margin:2px 0;
# }
# 
# /* AI 對話框 */
# textarea[data-testid="stChatInputTextArea"] {
#     color: #FFFFFF !important;
#     caret-color: #FFFFFF !important;
# }
# textarea[data-testid="stChatInputTextArea"]::placeholder {
#     color: #DDDDDD !important;
#     opacity: 1;
# }
# </style>
# """
# 
# def apply_global_style():
#     st.markdown(custom_css, unsafe_allow_html=True)

"""### 首頁"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile 首頁.py
# import os
# import sys
# import streamlit as st
# from shared.styles import apply_global_style
# from shared.resources import load_resources
# sys.path.append(os.path.dirname(os.path.abspath(__file__)))
# 
# st.set_page_config(layout='wide', page_title='CPBL 棒球分析系統')
# 
# apply_global_style()
# 
# model, df_stats = load_resources()
# 
# # 主頁
# st.markdown("""
# <div style="background-color: #001844; padding: 2rem; border-radius: 1rem; color: white; margin-bottom: 2rem;">
#     <h1 style='color: white; margin:0;'>CPBL 棒球分析系統</h1>
#     <p style='color: #cbd5e1; margin-top: 10px;'>帶你一起認識棒球!!</p>
# </div>
# """, unsafe_allow_html=True)
# 
# m1, m2, m3 = st.columns(3)
# m1.metric("模型準確率", "95.9%", "高準確率")
# m2.metric("已執行預測", "761 場", "場場收錄")
# m3.metric("歷史數據庫", "35 年", "年年都有")
# 
# st.markdown("### 🎧相關影片")
# 
# podcasts = [
#     {"title": "棒球報你知 Podcast EP.1 中職建軍大洗牌", "video_id": "68C5TK90YGk"},
#     {"title": "台灣大賽 Game 5 總冠軍賽精華片段", "video_id": "emVgQV6UyIM"}
# ]
# 
# cols = st.columns(len(podcasts) if len(podcasts) > 0 else 1)
# if len(podcasts) == 1:
#     cols = [st.columns([1, 2, 1])[1]]
# 
# for i, podcast in enumerate(podcasts):
#     with cols[i]:
#         embed_url = f"https://www.youtube.com/embed/{podcast['video_id']}"
#         card_html = f"""
#         <div class="podcast-card">
#             <div class="video-container">
#                 <iframe src="{embed_url}" title="YouTube video player"
#                 allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
#                 allowfullscreen></iframe>
#             </div>
#             <h3>{podcast['title']}</h3>
#         </div>
#         """
#         st.markdown(card_html, unsafe_allow_html=True)

"""### 未來賽事預測"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pages/2_🔮_未來賽事預測.py
# import streamlit as st
# import numpy as np
# import pandas as pd
# import plotly.graph_objects as go
# import os
# import joblib
# from sklearn.preprocessing import StandardScaler
# from shared.styles import apply_global_style
# 
# GITHUB_BASE = "https://raw.githubusercontent.com/ChewyChloe/cpbl-project/main/"
# MODEL_URL = GITHUB_BASE + "cpbl_ai_model.pkl"
# META_MODEL_URL = GITHUB_BASE + "cpbl_meta_learner.pkl"
# SCALER_URL = GITHUB_BASE + "scaler.pkl"
# BATTER_DATA_URL = GITHUB_BASE + "player_features_for_app.csv"
# PITCHER_DATA_URL = GITHUB_BASE + "pitcher_stats_for_app.csv"
# 
# PARK_FACTORS = {
#     "洲際": {"Runs": 1.19}, "澄清湖": {"Runs": 1.03}, "天母": {"Runs": 0.96},
#     "新莊": {"Runs": 0.90}, "樂天桃園": {"Runs": 1.18}, "台南": {"Runs": 0.91},
#     "台北大巨蛋": {"Runs": 0.84}
# }
# 
# STADIUM_MAP = {
#     "統一7-ELEVEn獅": ["台南"], "中信兄弟": ["洲際"], "樂天桃猿": ["樂天桃園"],
#     "味全龍": ["天母", "台北大巨蛋"], "富邦悍將": ["新莊"], "台鋼雄鷹": ["澄清湖"]
# }
# 
# TEAM_ROSTERS = {
#     "統一7-ELEVEn獅": {
#         "pitchers": ["陳韻文", "蒙德茲", "劉予承", "髙塩將樹", "鍾允華", "邱浩鈞", "王鏡銘", "獅帝芬", "吳承諭", "胡智爲", "李軍", "辛俊昇", "郭俊麟", "飛力獅"],
#         "batters": ["陳傑憲", "林安可", "蘇智傑", "陳鏞基", "潘傑楷", "邱智呈", "陳聖平", "陳重羽", "林佳緯", "胡金龍", "林子豪", "許哲晏", "陳重廷", "林泓弦", "林祖傑", "林岱安", "柯育民", "朱迦恩"]
#     },
#     "台鋼雄鷹": {
#         "pitchers": ["江承諺", "陳柏清", "艾速特", "黃群", "王躍霖", "林詩翔", "韋宏亮", "黃紹睿", "櫻井周斗", "許育銘", "張誠恩", "郭俞延"],
#         "batters": ["魔鷹", "曾子祐", "王柏融", "吳念庭", "王博玄", "杜家明", "郭阜林", "郭永維", "葉保弟", "陳文杰", "藍寅倫", "紀慶然", "顏郁軒", "林家鋐", "曾昱磬", "高聖恩", "陳致嘉", "陳世嘉"]
#     },
#     "中信兄弟": {
#         "pitchers": ["德保拉", "呂彥青", "吳俊偉", "蔡齊哲", "李振昌", "鄭凱文", "魏碩成", "林暉盛", "江忠城", "羅戈", "鄭浩均", "李博登", "盧孟揚", "伍立辰", "韋禮加"],
#         "batters": ["江坤宇", "王威晨", "許基宏", "陳俊秀", "岳政華", "曾頌恩", "詹子賢", "岳東華", "高宇杰", "張志豪", "王政順", "林志綱", "張仁瑋", "黃韋盛", "許庭綸", "宋晟睿", "陳統恩", "徐博瑋"]
#     },
#     "樂天桃猿": {
#         "pitchers": ["威能帝", "魔神樂", "黃子鵬", "陳冠宇", "陳柏豪", "蘇俊璋", "莊昕諺", "王志煊", "賴胤豪", "朱承洋", "凱樂", "邱駿威", "林子崴", "陳克羿"],
#         "batters": ["林立", "梁家榮", "廖健富", "陳晨威", "林承飛", "朱育賢", "林泓育", "馬傑森", "林子偉", "林智平", "成晉", "余德龍", "林政華", "何品室融", "鍾玉成", "許賀捷", "李勛傑", "宋嘉翔", "張閔勛", "嚴宏鈞"]
#     },
#     "味全龍": {
#         "pitchers": ["徐若熙", "鋼龍", "陳冠偉", "林凱威", "林子昱", "郭郁政", "陳禹勳", "曹祐齊", "張景淯", "呂偉晟", "李致霖", "趙璟榮", "陳志杰", "張鈞守", "黃暐傑", "林鋅杰"],
#         "batters": ["吉力吉撈．鞏冠", "李凱威", "劉基鴻", "郭天信", "張政禹", "蔣少宏", "拿莫．伊漾", "林孝程", "劉俊緯", "陳思仲", "周委宏", "瑪仕革斯．俄霸律尼", "朱育賢", "王順和", "張祐銘", "張祐嘉", "林辰勳"]
#     },
#     "富邦悍將": {
#         "pitchers": ["曾峻岳", "王尉永", "江國豪", "黃保羅", "賴鴻誠", "廖任磊", "范柏絜", "李吳永勤", "魔力藍", "力亞士", "游霆崴", "林栚呈"],
#         "batters": ["張育成", "申皓瑋", "范國宸", "戴培峰", "王正棠", "董子恩", "王念好", "池恩齊", "李宗賢", "林澤彬", "高捷", "葉子霆", "黃兆維", "林岳谷", "潘瑋祥", "陳真", "張洺瑀", "蔡佳諺", "周佳樂", "豊暐", "魏全"]
#     }
# }
# 
# @st.cache_resource
# def load_all_resources():
#     files = {"model.pkl": MODEL_URL, "meta.pkl": META_MODEL_URL, "scaler.pkl": SCALER_URL, "bat.csv": BATTER_DATA_URL, "pit.csv": PITCHER_DATA_URL}
#     for name, url in files.items():
#         if not os.path.exists(name): os.system(f"wget -q -O {name} {url}")
# 
#     df_b = pd.read_csv("bat.csv")
#     df_p = pd.read_csv("pit.csv")
#     df_b.columns = df_b.columns.str.strip()
#     df_p.columns = df_p.columns.str.strip()
# 
#     return joblib.load("model.pkl"), joblib.load("meta.pkl"), joblib.load("scaler.pkl"), df_b, df_p
# 
# model, meta_model, scaler, df_bat, df_pit = load_all_resources()
# 
# first_est = model.estimators_[0]
# current_order = first_est.feature_names_ if hasattr(first_est, 'feature_names_') else first_est.feature_names_in_
# 
# apply_global_style()
# st.header("🔮 2026 棒球比賽預測系統")
# 
# col_h, col_vs, col_a = st.columns([1, 0.2, 1])
# with col_h:
#     st.subheader("🏠 主隊 (Home)")
#     h_team = st.selectbox("選擇主隊", list(STADIUM_MAP.keys()), key="h_t")
#     h_stadium = st.selectbox("🏟️ 比賽球場", STADIUM_MAP[h_team], key="h_st")
#     h_sp = st.selectbox("⚾ 選擇先發投手", TEAM_ROSTERS[h_team]["pitchers"], key="h_p")
#     h_lineup = st.multiselect("📋 選擇打線 (9人)", TEAM_ROSTERS[h_team]["batters"], key="h_l")
# 
# with col_a:
#     st.subheader("✈️ 客隊 (Away)")
#     a_team = st.selectbox("選擇客隊", [t for t in STADIUM_MAP.keys() if t != h_team], key="a_t")
#     a_sp = st.selectbox("選擇先發投手", TEAM_ROSTERS[a_team]["pitchers"], key="a_p")
#     a_lineup = st.multiselect("選擇打線 (9人)", TEAM_ROSTERS[a_team]["batters"], key="a_l")
# 
# if st.button("🚀 執行預測", use_container_width=True):
#     if len(h_lineup) != 9 or len(a_lineup) != 9:
#         st.warning("⚠️ 請確保兩隊皆選滿 9 位打者。")
#     else:
#         with st.spinner("正在解析..."):
# 
#             def get_team_wraa(names, expected_order):
#                 wraa_total = 0
#                 found_names = []
#                 for name in names:
#                     hist = df_bat[
#                         (df_bat['Name_Display'].str.strip() == name.strip()) &
#                         (df_bat['Year_Display'].isin([2024, 2025]))
#                     ].sort_values('Year_Display', ascending=False)
# 
#                     if not hist.empty:
#                         found_names.append(name)
#                         weights = [0.7, 0.3]
#                         vals = []
#                         for i in range(min(2, len(hist))):
#                             row = hist.iloc[[i]]
#                             feat_raw = row.drop(columns=['Name_Display','Team_Display','Year_Display','Real_OPS'], errors='ignore')
#                             feat_aligned = feat_raw.reindex(columns=expected_order, fill_value=0)
#                             feat_aligned = feat_aligned.apply(pd.to_numeric, errors='coerce').fillna(0)
#                             vals.append(model.predict(feat_aligned)[0])
# 
#                         w_use = weights[:len(vals)]
#                         if sum(w_use) > 0:
#                             w_norm = [w/sum(w_use) for w in w_use]
#                             wraa_total += np.average(vals, weights=w_norm)
#                 return wraa_total, found_names
# 
#             # 計算打擊與投手數據
#             h_wraa, h_found = get_team_wraa(h_lineup, current_order)
#             a_wraa, a_found = get_team_wraa(a_lineup, current_order)
# 
#             def get_fip(name):
#                 name_col = 'Name' if 'Name' in df_pit.columns else 'Name_Display'
#                 res = df_pit[df_pit[name_col].str.strip() == name.strip()].sort_values('Year', ascending=False)['FIP']
#                 return res.values[0] if not res.empty else 4.2
# 
#             h_fip, a_fip = get_fip(h_sp), get_fip(a_sp)
#             pf_val = PARK_FACTORS[h_stadium]["Runs"]
# 
#             # 預測計算
#             wraa_diff = h_wraa - a_wraa
#             fip_diff = a_fip - h_fip
# 
#             X_raw = np.array([[wraa_diff, fip_diff, pf_val]])
#             X_scaled = scaler.transform(X_raw)
#             win_prob_raw = meta_model.predict_proba(X_scaled)[0][1]
# 
#             # 邏輯修正
#             adjustment = 0.33
#             logit_raw = np.log(win_prob_raw / (1 - win_prob_raw))
#             logit_final = logit_raw + adjustment
#             win_prob = 1 / (1 + np.exp(-logit_final))
#             win_prob = np.clip(win_prob, 0.05, 0.95)
# 
#             # 診斷面板
#             with st.expander("🔍 數據診斷與計算過程"):
#                 st.markdown("### 1. 打擊戰力 (wRAA)")
#                 st.write(f"- 主隊總預估 wRAA: `{h_wraa:.2f}`")
#                 st.write(f"- 客隊總預估 wRAA: `{a_wraa:.2f}`")
#                 st.info(f"💡 **打擊差距 (wraa_diff)** = `{wraa_diff:.2f}`")
# 
#                 st.markdown("---")
#                 st.markdown("### 2. 投手壓制力 (FIP)")
#                 st.write(f"- 主隊先發 ({h_sp}) FIP: `{h_fip:.2f}`")
#                 st.write(f"- 客隊先發 ({a_sp}) FIP: `{a_fip:.2f}`")
#                 st.info(f"💡 **投手差距 (fip_diff)** = `{fip_diff:.2f}`")
# 
#                 st.markdown("---")
#                 st.markdown("### 3. 最終推論與修正")
#                 st.write(f"- 球場因子 (PF): `{pf_val:.2f}`")
#                 st.write(f"- 模型原始預測: `{win_prob_raw*100:.2f}%`")
# 
#                 st.latex(r"Logit_{raw} = \ln\left(\frac{P_{raw}}{1-P_{raw}}\right) = " + f"{logit_raw:.3f}")
#                 st.write(f"- 主場修正強度: `+{adjustment}`")
#                 st.latex(r"Prob_{final} = \frac{1}{1 + e^{-(Logit_{raw} + " + str(adjustment) + ")}}")
# 
#                 st.success(f"修正後最終勝率: **{win_prob*100:.2f}%**")
# 
#             # 圖表
#             fig = go.Figure(go.Indicator(
#                 mode = "gauge+number", value = win_prob * 100,
#                 title = {'text': f"{h_team} 勝率預估 (%)"},
#                 gauge = {
#                     'axis': {'range': [0, 100]},
#                     'bar': {'color': "#002D62"},
#                     'steps': [
#                         {'range': [0, 45], 'color': "#FFCCCC"},
#                         {'range': [45, 55], 'color': "#EEEEEE"},
#                         {'range': [55, 100], 'color': "#CCFFCC"}
#                     ]
#                 }
#             ))
#             st.plotly_chart(fig, use_container_width=True)
# 
#             if win_prob > 0.55: st.success(f"**AI 評論**：{h_team} 在 {h_stadium} 具有明顯優勢。")
#             elif win_prob < 0.45: st.error(f"**AI 評論**：客隊 {a_team} 的戰力預期較為強勢。")
#             else: st.info("**AI 評論**：雙方戰力平衡，主場因素將是勝負關鍵。")

"""### 數據儀表板"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pages/1_📊_數據儀表板.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# import plotly.graph_objects as go
# import sys
# import os
# 
# sys.path.append(os.path.abspath('.'))
# try:
#     from shared import styles
# except ImportError:
#     pass
# 
# st.set_page_config(page_title="CPBL 數據儀表板", layout="wide")
# st.title("⚾ CPBL 職棒數據分析中心")
# 
# @st.cache_data
# def load_data():
#     try:
#         df = pd.read_csv('baseball_data.csv')
#     except FileNotFoundError:
#         st.error("找不到 'baseball_data.csv'")
#         return pd.DataFrame(), pd.DataFrame()
# 
#     cols_to_numeric = ['bat_PA', 'pit_IP', 'pit_ER', 'pit_BB', 'pit_H', 'pit_SO']
#     for col in cols_to_numeric:
#         if col in df.columns:
#             df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)
# 
#     team_name_map = {
#         '統一獅': '統一7-ELEVEn獅', '統一': '統一7-ELEVEn獅', 'Uni-Lions': '統一7-ELEVEn獅',
#         '桃猿': '樂天桃猿', 'Lamigo': '樂天桃猿', 'Rakuten': '樂天桃猿', '樂天': '樂天桃猿',
#         '兄弟': '中信兄弟', '兄弟象': '中信兄弟', 'Brothers': '中信兄弟',
#         '富邦': '富邦悍將', '悍將': '富邦悍將', '義大': '富邦悍將', '義大犀牛': '富邦悍將',
#         '味全': '味全龍', 'Dragons': '味全龍',
#         '台鋼': '台鋼雄鷹', 'TSG': '台鋼雄鷹'
#     }
#     target_teams = ['統一7-ELEVEn獅', '台鋼雄鷹', '中信兄弟', '樂天桃猿', '味全龍', '富邦悍將']
# 
#     # 打者資料
#     bat_cols = ['Name_clean', 'Team Name_x', 'Year', 'bat_PA', 'bat_AB', 'bat_H', 'bat_HR', 'bat_SB', 'bat_AVG', 'bat_OPS', 'bat_OBP', 'bat_SLG']
#     valid_bat_cols = [c for c in bat_cols if c in df.columns]
# 
#     df_sorted_bat = df[valid_bat_cols].sort_values(by=['Year', 'bat_PA'], ascending=[False, False])
#     df_bat = df_sorted_bat.drop_duplicates(subset=['Name_clean', 'Year'], keep='first')
# 
#     df_bat = df_bat.rename(columns={'Name_clean': 'Name', 'Team Name_x': 'Team', 'bat_OPS': 'OPS', 'bat_AVG': 'AVG', 'bat_HR': 'HR', 'bat_SB': 'SB', 'bat_PA': 'PA'})
#     df_bat['Team'] = df_bat['Team'].replace(team_name_map)
#     df_bat = df_bat[df_bat['Team'].isin(target_teams)]
#     df_bat = df_bat[df_bat['PA'] > 0]
# 
#     # 投手資料
#     df_pit_raw = df[ (df['pit_IP'] > 0) & (df['bat_PA'] < 10) ].copy()
# 
#     if 'pit_ER' in df_pit_raw.columns and 'pit_IP' in df_pit_raw.columns:
#         df_pit_raw['pit_ERA'] = (df_pit_raw['pit_ER'] * 9) / df_pit_raw['pit_IP'].replace(0, 0.1)
#     else:
#         df_pit_raw['pit_ERA'] = 0.0
# 
#     if 'pit_BB' in df_pit_raw.columns and 'pit_H' in df_pit_raw.columns:
#          df_pit_raw['pit_WHIP'] = (df_pit_raw['pit_BB'] + df_pit_raw['pit_H']) / df_pit_raw['pit_IP'].replace(0, 0.1)
#     else:
#         df_pit_raw['pit_WHIP'] = 0.0
# 
#     pit_cols = ['Name_clean', 'Team Name_y', 'Year', 'pit_ERA', 'pit_IP', 'pit_SO', 'pit_BB', 'pit_WHIP']
#     valid_pit_cols = [c for c in pit_cols if c in df_pit_raw.columns]
# 
#     df_sorted_pit = df_pit_raw[valid_pit_cols].sort_values(by=['Year', 'pit_IP'], ascending=[False, False])
#     df_pit = df_sorted_pit.drop_duplicates(subset=['Name_clean', 'Year'], keep='first')
# 
#     df_pit = df_pit.rename(columns={'Name_clean': 'Name', 'Team Name_y': 'Team', 'pit_ERA': 'ERA', 'pit_IP': 'IP', 'pit_SO': 'SO', 'pit_BB': 'BB', 'pit_WHIP': 'WHIP'})
#     df_pit['Team'] = df_pit['Team'].fillna('Unknown')
#     df_pit['Team'] = df_pit['Team'].replace(team_name_map)
#     df_pit = df_pit[df_pit['Team'].isin(target_teams)]
# 
#     return df_bat, df_pit
# 
# df_bat, df_pit = load_data()
# 
# # 分頁內容
# tab1, tab2, tab3 = st.tabs(["🏆 聯盟戰況", "🏏 打擊排行", "⚾ 投手分析"])
# 
# def get_weighted_average(data, value_col, weight_col):
#     if data[weight_col].sum() == 0: return 0
#     return np.average(data[value_col], weights=data[weight_col])
# 
# # Tab 1: 聯盟戰況
# with tab1:
#     st.subheader("🛠️ 篩選條件")
#     all_years = sorted(df_bat['Year'].unique())
#     def_year = [2024] if 2024 in all_years else ([max(all_years)] if all_years else [])
# 
#     t1_years = st.multiselect("選擇年份 (僅影響下方氣泡圖)", all_years, default=def_year, key="t1_year")
# 
#     # 資料篩選
#     bat_t1 = df_bat[df_bat['Year'].isin(t1_years)]
#     pit_t1 = df_pit[df_pit['Year'].isin(t1_years)]
# 
#     st.divider()
#     st.header("團隊戰力分析")
# 
#     col1, col2 = st.columns(2)
# 
#     with col1:
#         st.subheader("📈 團隊 OPS 年度趨勢")
#         team_ops_trend = df_bat.groupby(['Year', 'Team']).apply(
#             lambda x: pd.Series({'OPS': get_weighted_average(x, 'OPS', 'PA')})
#         ).reset_index()
# 
#         if not team_ops_trend.empty:
#             fig_trend = px.line(team_ops_trend, x='Year', y='OPS', color='Team', markers=True)
#             st.plotly_chart(fig_trend, use_container_width=True)
# 
#     with col2:
#         st.subheader("🛡️ 比較攻守表現：OPS vs ERA")
#         team_ops_now = bat_t1.groupby(['Year', 'Team']).apply(
#             lambda x: pd.Series({'OPS': get_weighted_average(x, 'OPS', 'PA')})
#         ).reset_index()
# 
#         if not pit_t1.empty:
#             team_era_now = pit_t1.groupby(['Year', 'Team']).apply(
#                 lambda x: pd.Series({'ERA': get_weighted_average(x, 'ERA', 'IP')})
#             ).reset_index()
#             team_stats = pd.merge(team_ops_now, team_era_now, on=['Year', 'Team'], how='left')
#         else:
#             team_stats = team_ops_now
# 
#         if 'ERA' in team_stats.columns and not team_stats.empty:
#             avg_era = team_stats['ERA'].mean()
#             avg_ops = team_stats['OPS'].mean()
# 
#             fig_quad = px.scatter(
#                 team_stats, x='ERA', y='OPS', color='Team',
#                 text='Year', size=[15]*len(team_stats), hover_name='Team'
#             )
#             fig_quad.add_vline(x=avg_era, line_dash="dash", line_color="gray", annotation_text="平均ERA")
#             fig_quad.add_hline(y=avg_ops, line_dash="dash", line_color="gray", annotation_text="平均OPS")
#             fig_quad.update_layout(xaxis=dict(autorange="reversed"))
# 
#             if len(t1_years) == 1:
#                 fig_quad.update_layout(title=f"{t1_years[0]} 年賽季戰力分佈")
# 
#             st.plotly_chart(fig_quad, use_container_width=True)
#         else:
#             st.info("請選擇年份以顯示資料")
# 
# # Tab 2: 打擊排行
# with tab2:
#     st.header("打擊數據排行榜")
# 
#     max_pa_val = int(df_bat['PA'].max()) if not df_bat.empty else 100
#     min_pa = st.slider("最少打席數 (PA)", 0, max_pa_val, 50, key="t2_slider")
# 
#     bat_display = df_bat[df_bat['PA'] >= min_pa].sort_values('OPS', ascending=False)
# 
#     col1, col2 = st.columns([2, 1])
#     with col1:
#         st.subheader("💥 強打者分佈 (PA vs OPS)")
#         fig = px.scatter(bat_display, x='PA', y='OPS', color='Team', hover_name='Name', size='HR')
#         if not bat_display.empty:
#             fig.add_hline(y=bat_display['OPS'].mean(), line_dash="dash", annotation_text="平均")
#         st.plotly_chart(fig, use_container_width=True)
# 
#     with col2:
#         st.subheader("📊 排行榜")
#         st.dataframe(
#             bat_display[['Name', 'Team', 'OPS', 'AVG', 'HR', 'SB', 'Year']],
#             column_config={
#                 "OPS": st.column_config.ProgressColumn("OPS", min_value=0, max_value=1.5, format="%.3f"),
#                 "AVG": st.column_config.NumberColumn("AVG", format="%.3f"),
#                 "Year": st.column_config.NumberColumn("年份", format="%d")
#             },
#             height=500,
#             hide_index=True
#         )
# 
# # Tab 3: 投手分析
# with tab3:
#     st.subheader("🛠️ 篩選條件")
# 
#     t3_teams = st.multiselect("選擇球隊", df_pit['Team'].unique(), default=df_pit['Team'].unique(), key="t3_team")
#     pit_t3 = df_pit[df_pit['Team'].isin(t3_teams)]
# 
#     st.divider()
#     st.header("投手進階數據")
# 
#     if pit_t3.empty:
#         st.warning("⚠️ 篩選條件下無投手資料")
#     else:
#         col1, col2 = st.columns([1, 1])
#         with col1:
#             st.subheader("🎯 三振 (SO) vs 防禦率 (ERA)")
#             fig = px.scatter(pit_t3, x='SO', y='ERA', color='Team', hover_name='Name', size='IP')
#             fig.update_layout(yaxis=dict(range=[10, 0], title="ERA (防禦率)"))
#             st.plotly_chart(fig, use_container_width=True)
# 
#         with col2:
#             st.subheader("🕸️ 投手能力雷達圖")
#             df_radar = pit_t3[['Name', 'ERA', 'WHIP', 'SO', 'BB', 'IP']].copy()
# 
#             target = st.selectbox("選擇投手", df_radar['Name'].unique(), key="t3_select")
# 
#             if target:
#                 metrics = {'ERA': False, 'WHIP': False, 'SO': True, 'BB': False, 'IP': True}
#                 for col, higher_is_better in metrics.items():
#                     min_val = df_radar[col].min()
#                     max_val = df_radar[col].max()
#                     if max_val == min_val:
#                         df_radar[f'{col}_Score'] = 50
#                     else:
#                         if higher_is_better:
#                             df_radar[f'{col}_Score'] = (df_radar[col] - min_val) / (max_val - min_val) * 100
#                         else:
#                             df_radar[f'{col}_Score'] = (max_val - df_radar[col]) / (max_val - min_val) * 100
# 
#                 p_data = df_radar[df_radar['Name'] == target].iloc[0]
#                 avg_score = df_radar[[f'{k}_Score' for k in metrics.keys()]].mean()
#                 categories = list(metrics.keys())
#                 player_scores = [p_data[f'{c}_Score'] for c in categories]
#                 league_avg_scores = [avg_score[f'{c}_Score'] for c in categories]
# 
#                 fig = go.Figure()
#                 fig.add_trace(go.Scatterpolar(r=player_scores, theta=categories, fill='toself', name=p_data['Name'], line_color='blue'))
#                 fig.add_trace(go.Scatterpolar(r=league_avg_scores, theta=categories, fill='toself', name='聯盟平均', line_color='gray', opacity=0.5))
#                 fig.update_layout(polar=dict(radialaxis=dict(visible=True, range=[0, 100])), title=f"能力值評分 (0-100)")
#                 st.plotly_chart(fig, use_container_width=True)
#                 st.caption("註：圖表顯示的是「PR評分」(0~100)，越外圈代表該項能力在聯盟中越強。")

"""### 深度論壇

* wSB = SB * runSB + CS * runCS – lgwSB * (1B + BB + HBP – IBB)
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pages/3_💬_深度論壇.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# import plotly.graph_objects as go
# import sys
# import os
# 
# sys.path.append(os.path.abspath('.'))
# try:
#     from shared import styles
#     styles.apply_global_style()
# except ImportError:
#     pass
# 
# st.set_page_config(page_title="深度數據論壇", layout="wide")
# 
# st.markdown("""
#     <style>
#     /* 確保樣式正確 */
#     section[data-testid="stSidebar"] { background-color: #001844 !important; }
#     section[data-testid="stSidebar"] * { color: #FFFFFF !important; }
#     [data-testid="stMain"] h1, [data-testid="stMain"] h2, [data-testid="stMain"] h3 {
#         color: #000000 !important;
#         font-weight: bold !important;
#     }
#     </style>
# """, unsafe_allow_html=True)
# 
# st.title("💬 深度數據論壇")
# st.markdown("### ⚾ Sabermetrics：用進階數據看棒球")
# 
# @st.cache_data
# def load_data():
#     try:
#         df = pd.read_csv('baseball_data.csv')
#     except FileNotFoundError:
#         st.error("找不到資料檔")
#         return pd.DataFrame()
# 
#     numeric_cols = [
#         'bat_PA', 'bat_AB', 'bat_R', 'bat_H', 'bat_2B', 'bat_3B', 'bat_HR',
#         'bat_SF', 'bat_SH', 'bat_BB', 'bat_IBB', 'bat_HBP',
#         'bat_SO', 'bat_SB', 'bat_CS', 'bat_GIDP',
#         'bat_AVG', 'bat_OPS'
#     ]
#     for c in numeric_cols:
#         if c in df.columns:
#             df[c] = pd.to_numeric(df[c], errors='coerce').fillna(0)
# 
#     # 計算
#     # 一壘安打 (1B) = H - 2B - 3B - HR
#     if 'bat_H' in df.columns and 'bat_2B' in df.columns:
#         df['bat_1B'] = df['bat_H'] - df['bat_2B'] - df['bat_3B'] - df['bat_HR']
#     else:
#         df['bat_1B'] = 0
# 
#     team_map = {
#         '統一獅': '統一7-ELEVEn獅', '統一': '統一7-ELEVEn獅',
#         '桃猿': '樂天桃猿', 'Lamigo': '樂天桃猿', 'Rakuten': '樂天桃猿',
#         '兄弟': '中信兄弟', '兄弟象': '中信兄弟',
#         '富邦': '富邦悍將', '義大': '富邦悍將',
#         '味全': '味全龍', '台鋼': '台鋼雄鷹'
#     }
#     target_teams = ['統一7-ELEVEn獅', '台鋼雄鷹', '中信兄弟', '樂天桃猿', '味全龍', '富邦悍將']
# 
#     cols_needed = [
#         'Name_clean', 'Team Name_x', 'Year',
#         'bat_PA', 'bat_AB', 'bat_R', 'bat_H', 'bat_1B', 'bat_BB', 'bat_HBP', 'bat_IBB',
#         'bat_SF', 'bat_AVG', 'bat_OPS', 'bat_SB', 'bat_CS'
#     ]
#     valid_cols = [c for c in cols_needed if c in df.columns]
# 
#     df_sorted = df[valid_cols].sort_values(by=['Year', 'bat_PA'], ascending=[False, False])
#     df_bat = df_sorted.drop_duplicates(subset=['Name_clean', 'Year'], keep='first')
# 
#     rename_dict = {
#         'Name_clean': 'Name', 'Team Name_x': 'Team',
#         'bat_OPS': 'OPS', 'bat_AVG': 'AVG',
#         'bat_SB': 'SB', 'bat_CS': 'CS', 'bat_PA': 'PA',
#         'bat_1B': '1B', 'bat_BB': 'BB', 'bat_HBP': 'HBP', 'bat_IBB': 'IBB',
#         'bat_R': 'R', 'bat_AB': 'AB', 'bat_H': 'H', 'bat_SF': 'SF'
#     }
#     df_bat = df_bat.rename(columns={k:v for k,v in rename_dict.items() if k in df_bat.columns})
# 
#     df_bat['Team'] = df_bat['Team'].replace(team_map)
#     df_bat = df_bat[df_bat['Team'].isin(target_teams)]
#     df_bat = df_bat[df_bat['PA'] > 0]
# 
#     return df_bat
# 
# df = load_data()
# 
# if df.empty:
#     st.stop()
# 
# # 議題選擇
# topic = st.radio(
#     "請選擇想要探討的議題：",
#     ["📉 議題一：打擊率 (AVG) 是不是過時了？", "🏃 議題二：盜壘價值 (wSB) 的應用"],
#     horizontal=True
# )
# 
# st.divider()
# 
# # 議題一：打擊率 vs OPS
# if "議題一" in topic:
#     st.header("📉 打擊率 (AVG) vs 整體攻擊指數 (OPS)")
#     st.markdown("""
#     **傳統觀點**：打擊率 (AVG) 是衡量打者好壞的最重要指標。
#     **數據觀點**：打擊率忽略了「選球眼 (保送)」和「長打能力 (全壘打)」，打擊率高的球員貢獻度可能不如打擊率低者。
#     """)
# 
#     col1, col2 = st.columns(2)
#     sel_year = col1.selectbox("選擇年份", sorted(df['Year'].unique(), reverse=True))
#     min_pa = col2.slider("過濾：最少打席數 (PA)", 0, 500, 100)
# 
#     df_topic1 = df[(df['Year'] == sel_year) & (df['PA'] >= min_pa)].copy()
# 
#     if not df_topic1.empty:
#         corr = df_topic1['AVG'].corr(df_topic1['OPS'])
#         st.info(f"💡 **數據發現**：在 {sel_year} 年，打擊率與 OPS 的相關係數為 **{corr:.2f}**。")
# 
#         fig = px.scatter(
#             df_topic1, x='AVG', y='OPS',
#             color='Team', size='PA', hover_name='Name',
#             text='Name',
#             title=f"{sel_year} 年打者分佈：AVG vs OPS"
#         )
#         avg_mean = df_topic1['AVG'].mean()
#         ops_mean = df_topic1['OPS'].mean()
#         fig.add_vline(x=avg_mean, line_dash="dash", line_color="gray", annotation_text="平均AVG")
#         fig.add_hline(y=ops_mean, line_dash="dash", line_color="gray", annotation_text="平均OPS")
#         st.plotly_chart(fig, use_container_width=True)
#     else:
#         st.warning("此條件下無資料。")
# 
# # 議題二：盜壘運用
# elif "議題二" in topic:
#     st.header("🏃 盜壘分析")
# 
#     st.markdown("""
#     我們採用 **FanGraphs** 的 **wSB** 公式來計算盜壘對球隊的真實得分貢獻。
# 
#     $$
#     wSB = (SB \\times runSB) + (CS \\times runCS) - (lgwSB \\times (1B + BB + HBP - IBB))
#     $$
# 
#     * **runSB (0.2)**：盜壘成功的得分期望值。
#     * **runCS (約 -0.4)**：盜壘失敗的扣分，根據當年度的得分環境動態計算。
#     * **lgwSB**：聯盟平均值，用來扣除「平均跑者在同樣上壘機會下應有的貢獻」。
#     """)
# 
#     # 篩選
#     col1, col2 = st.columns(2)
#     sel_years = col1.multiselect("選擇年份", sorted(df['Year'].unique(), reverse=True), default=[2024, 2025] if 2024 in df['Year'].unique() else [df['Year'].max()])
#     min_sb_attempt = col2.slider("過濾：最少嘗試盜壘次數 (SB+CS)", 0, 30, 5)
# 
#     df_topic2 = df[df['Year'].isin(sel_years)].copy()
# 
#     # 計算 wSB 參數
#     if not df_topic2.empty:
#         # 計算聯盟總和
#         lg_R = df_topic2['R'].sum()
#         # 估算 Outs (Outs = AB - H + CS + SF)
#         lg_Outs = (df_topic2['AB'].sum() - df_topic2['H'].sum()) + df_topic2['CS'].sum() + df_topic2['SF'].sum()
#         if lg_Outs == 0: lg_Outs = 1
# 
#         # 動態計算 runCS (FanGraphs 公式: 2 * R/Outs + 0.075)
#         runs_per_out = lg_R / lg_Outs
#         runSB = 0.2
#         runCS = -1 * (2 * runs_per_out + 0.075)
# 
#         # 計算 lgwSB
#         lg_SB = df_topic2['SB'].sum()
#         lg_CS = df_topic2['CS'].sum()
#         # 上壘機會 (Singles + BB + HBP - IBB)
#         lg_1B = df_topic2['1B'].sum()
#         lg_BB = df_topic2['BB'].sum()
#         lg_HBP = df_topic2['HBP'].sum()
#         lg_IBB = df_topic2['IBB'].sum()
# 
#         lg_opportunities = lg_1B + lg_BB + lg_HBP - lg_IBB
#         if lg_opportunities == 0: lg_opportunities = 1
# 
#         lgwSB = (lg_SB * runSB + lg_CS * runCS) / lg_opportunities
# 
#         def calculate_wSB(row):
#             opportunities = row['1B'] + row['BB'] + row['HBP'] - row['IBB']
#             # wSB
#             val = (row['SB'] * runSB) + (row['CS'] * runCS) - (lgwSB * opportunities)
#             return val
# 
#         df_topic2['wSB'] = df_topic2.apply(calculate_wSB, axis=1)
#         df_topic2['Attempt'] = df_topic2['SB'] + df_topic2['CS']
# 
#         # 過濾
#         df_filtered = df_topic2[df_topic2['Attempt'] >= min_sb_attempt].copy()
#         df_filtered['SB_Rate'] = df_filtered.apply(lambda x: (x['SB']/x['Attempt']*100) if x['Attempt']>0 else 0, axis=1)
# 
#         st.info(f"📊 **本期參數**：runCS (失敗扣分) = **{runCS:.3f}** (約為成功的 {abs(runCS/runSB):.1f} 倍代價)")
# 
#         # 表 1: wSB 排行榜
#         st.subheader("🏆 wSB 排行榜：誰是真正的盜壘貢獻王？")
#         st.caption("wSB > 0 代表比聯盟平均跑者貢獻更多分數；wSB < 0 代表拖累球隊。")
# 
#         top_n = 10
#         df_rank = df_filtered.sort_values('wSB', ascending=True).tail(top_n)
#         df_bottom = df_filtered.sort_values('wSB', ascending=True).head(5)
#         df_chart = pd.concat([df_bottom, df_rank]).drop_duplicates().sort_values('wSB')
# 
#         colors = ['red' if x < 0 else '#2E5090' for x in df_chart['wSB']]
# 
#         fig = go.Figure()
#         fig.add_trace(go.Bar(
#             y=df_chart['Name'], x=df_chart['wSB'],
#             orientation='h', marker_color=colors,
#             text=df_chart['wSB'].apply(lambda x: f"{x:.2f}"),
#             textposition='auto',
#             hovertemplate="<b>%{y}</b><br>SB: %{customdata[0]}<br>CS: %{customdata[1]}<br>wSB: %{x:.2f}<extra></extra>",
#             customdata=df_chart[['SB', 'CS']]
#         ))
#         fig.update_layout(title="Weighted Stolen Base Runs (wSB)", xaxis_title="wSB (分數貢獻)", height=600)
#         st.plotly_chart(fig, use_container_width=True)
# 
#         # 表 2：高成功率不代表高貢獻
#         st.subheader("📉 成功率 vs wSB：高成功率不代表高貢獻")
#         fig2 = px.scatter(
#             df_filtered, x='SB_Rate', y='wSB',
#             color='Team', size='Attempt', hover_name='Name',
#             text='Name',
#             labels={'SB_Rate': '盜壘成功率 (%)', 'wSB': 'wSB (得分貢獻)'},
#             title="有些球員成功率高(右邊)，但因為跑得少或機會成本高，wSB 其實不高"
#         )
#         fig2.add_hline(y=0, line_dash="solid", line_color="gray")
#         fig2.add_vline(x=75, line_dash="dash", line_color="red", annotation_text="75% 及格線")
#         st.plotly_chart(fig2, use_container_width=True)
# 
#         # 結論
#         best = df_filtered.loc[df_filtered['wSB'].idxmax()]
#         worst = df_filtered.loc[df_filtered['wSB'].idxmin()]
# 
#         st.success(f"🥇 **最佳跑者**：**{best['Name']}** (wSB {best['wSB']:.2f})。他在扣除失敗風險與機會成本後，依然為球隊創造了顯著價值。")
#         if worst['wSB'] < 0:
#             st.error(f"⚠️ **負分跑者**：**{worst['Name']}** (wSB {worst['wSB']:.2f})。雖然他可能跑了不少，但相對於聯盟平均，他的跑壘策略其實是在減少球隊得分期望值。")
# 
#     else:
#         st.warning("⚠️ 此條件下無資料")

"""### AI_球探對話"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pages/4_🧑‍💼_AI_球探對話.py
# import streamlit as st
# import os
# import requests
# import time
# from google import genai
# from google.genai import types
# from shared.styles import apply_global_style
# 
# apply_global_style()
# st.header("🧑‍💼 AI 對話系統")
# 
# gemini_key = "AIzaSyBN5FU3Wk-DcFeRwINM9F6jBLwmS94chng"
# client = genai.Client(api_key=gemini_key)
# 
# GITHUB_USER = "ChewyChloe"
# GITHUB_REPO = "cpbl-project"
# GITHUB_FOLDER = "AI_RAG"
# GITHUB_API_URL = f"https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/contents/{GITHUB_FOLDER}"
# TARGET_STORE_NAME = "CPBL_Scout_Knowledge_v6"
# 
# @st.cache_resource(show_spinner="同步 GitHub 知識庫")
# def auto_initialize_rag(_client):
#     store = None
# 
#     try:
#         for s in _client.file_search_stores.list():
#             if s.display_name == TARGET_STORE_NAME:
#                 store = s
#                 break
#     except Exception:
#         pass
# 
#     if not store:
#         try:
#             store = _client.file_search_stores.create(
#                 config={'display_name': TARGET_STORE_NAME}
#             )
#         except Exception as e:
#             print(f"建立 Store 失敗: {e}")
#             return None
# 
#     existing_files = []
#     try:
#         pager = _client.file_search_stores.list_files(file_search_store_name=store.name)
#         existing_files = list(pager)
#     except:
#         pass
# 
#     if len(existing_files) == 0:
#         try:
#             res = requests.get(GITHUB_API_URL)
#             if res.status_code == 200:
#                 files_metadata = res.json()
#                 for i, file_info in enumerate(files_metadata):
#                     original_name = file_info['name']
#                     lower_name = original_name.lower()
# 
#                     if lower_name.endswith(('.pdf', '.txt', '.docx')):
#                         f_res = requests.get(file_info['download_url'])
# 
#                         if f_res.status_code == 200:
#                             safe_ext = ".pdf" if ".pdf" in lower_name else ".txt" if ".txt" in lower_name else ".docx"
#                             safe_temp_name = f"temp_doc_{i}{safe_ext}"
# 
#                             with open(safe_temp_name, "wb") as f:
#                                 f.write(f_res.content)
# 
#                             if os.path.getsize(safe_temp_name) > 0:
#                                 mime_type = "application/pdf"
#                                 if safe_ext == ".txt": mime_type = "text/plain"
#                                 elif safe_ext == ".docx": mime_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
# 
#                                 try:
#                                     _client.file_search_stores.upload_to_file_search_store(
#                                         file=safe_temp_name,
#                                         file_search_store_name=store.name,
#                                         config={
#                                             'display_name': original_name,
#                                             'mime_type': mime_type
#                                         }
#                                     )
#                                     time.sleep(1)
#                                 except Exception as e:
#                                     print(f"上傳失敗: {e}")
# 
#                             if os.path.exists(safe_temp_name):
#                                 os.remove(safe_temp_name)
#         except Exception as e:
#             print(f"GitHub 同步錯誤: {e}")
# 
#     return store.name if store else None
# 
# # 初始化
# store_name = auto_initialize_rag(client)
# 
# if not store_name:
#     st.error("⚠️ 知識庫初始化失敗。")
#     st.stop()
# 
# # 對話介面
# if "messages" not in st.session_state:
#     st.session_state.messages = []
# 
# for msg in st.session_state.messages:
#     with st.chat_message(msg["role"]):
#         st.markdown(msg["content"])
# 
# if prompt := st.chat_input("請教專業球探分析..."):
#     st.session_state.messages.append({"role": "user", "content": prompt})
#     with st.chat_message("user"):
#         st.markdown(prompt)
# 
#     with st.chat_message("assistant"):
#         with st.spinner("思考中..."):
#             try:
#                 response = client.models.generate_content(
#                     model="gemini-2.5-flash",
#                     contents=prompt,
#                     config={
#                         "tools": [{
#                             "file_search": {
#                                 "file_search_store_names": [store_name]
#                             }
#                         }],
#                         "system_instruction": """
#                         你是一位專業的棒球研究員。
#                         1. 當使用者問到具體數據或球探報告時，請優先參考「知識庫」中的檔案回答。
#                         2. 如果知識庫中沒有相關資訊，或者使用者是在問一般棒球規則、歷史或閒聊，請善用你的「通用棒球知識」直接回答。
#                         3. 回答時請保持專業、客觀，絕對不可提及"資料庫"、"根據我們手邊的資料"或"根據..."。
#                         4. 語氣輕鬆不嚴肅
#                         5. 名字：Brian
#                         """
#                     }
#                 )
#                 st.markdown(response.text)
#                 st.session_state.messages.append({"role": "assistant", "content": response.text})
# 
#             except Exception as e:
#                 st.error(f"生成回應時發生錯誤: {e}")

"""### 成員卡牌

import google.generativeai as genai
import time
from google.colab import files

MY_API_KEY = "AIzaSyBN5FU3Wk-DcFeRwINM9F6jBLwmS94chng"

genai.configure(api_key=MY_API_KEY)
model = genai.GenerativeModel('gemini-2.5-flash')

df = pd.read_csv("https://raw.githubusercontent.com/ChewyChloe/cpbl-project/d58371c954f80fac88be0eaf55943453dfe3ee0a/baseball_data.csv")

required_cols = ['bat_AVG', 'bat_OPS', 'bat_HR', 'pit_ERA', 'pit_W', 'pit_SO', 'pit_WHIP', 'pit_IP']
for c in required_cols:
    if c not in df.columns: df[c] = 0
    df[c] = pd.to_numeric(df[c], errors='coerce').fillna(0)

TARGET_PLAYERS = ['江坤宇', '林立', '陳冠宇', '陳傑憲']
commentaries = {}

for player_name in TARGET_PLAYERS:
    p_rows = df[df['Name_clean'] == player_name].sort_values('Year', ascending=False)

    if p_rows.empty:
        print(f"⚠️ 找不到 {player_name}")
        continue

    data = p_rows.iloc[0]
    is_pitcher = data.get('pit_IP', 0) > 0

    if is_pitcher:
        stats = f"防禦率 {data.get('pit_ERA', 0):.2f}, 勝投 {int(data.get('pit_W', 0))}, WHIP {data.get('pit_WHIP', 0):.2f}"
        role = "投手"
    else:
        stats = f"打擊率 {data.get('bat_AVG', 0):.3f}, OPS {data.get('bat_OPS', 0):.3f}, 全壘打 {int(data.get('bat_HR', 0))}"
        role = "打者"

    prompt = f"請用專業棒球球評口吻，針對中華職棒{role}「{player_name}」寫一段約80字的短評。重點數據：{stats}。風格要專業。"

    try:
        response = model.generate_content(prompt)
        comment = response.text.strip()
        commentaries[player_name] = comment
        print(f"{player_name} 完成")
    except Exception as e:
        print(f"{player_name} 失敗: {e}")

    time.sleep(2)

filename = "player_commentaries.json"
with open(filename, "w", encoding="utf-8") as f:
    json.dump(commentaries, f, ensure_ascii=False, indent=4)
files.download(filename)
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pages/5_⚾_球員卡牌.py
# import streamlit as st
# import pandas as pd
# import plotly.graph_objects as go
# import requests
# import json
# 
# st.set_page_config(page_title="球員介面", page_icon="🃏", layout="wide")
# 
# JSON_URL = "https://raw.githubusercontent.com/ChewyChloe/cpbl-project/refs/heads/main/player_commentary.json"
# DATA_URL = "https://raw.githubusercontent.com/ChewyChloe/cpbl-project/d58371c954f80fac88be0eaf55943453dfe3ee0a/baseball_data.csv"
# 
# # 球員名單、照片
# TARGET_PLAYERS = ['江坤宇', '林立', '陳冠宇', '陳傑憲']
# PLAYER_PHOTOS = {
#     '江坤宇': 'https://imgcdn.cna.com.tw/www/WebPhotos/800/20241001/824x1024_wmkn_0_C20241001000234.jpg',
#     '林立': 'https://img.ltn.com.tw/Upload/sports/page/800/2023/12/22/120.jpg',
#     '陳冠宇': 'https://hips.hearstapps.com/hmg-prod/images/pitcher-chen-kuan-yu-of-chinese-taipei-reacts-at-the-end-of-news-photo-1732522777.jpg',
#     '陳傑憲': 'https://img.ltn.com.tw/Upload/sports/page/800/2025/06/04/121.jpg'
# }
# TEAM_FIX = {
#     '江坤宇': '中信兄弟',
#     '林立': '樂天桃猿',
#     '陳冠宇': '樂天桃猿',
#     '陳傑憲': '統一獅'
# }
# 
# @st.cache_data
# def load_data():
#     try:
#         df = pd.read_csv(DATA_URL)
#         numeric_cols = ['bat_AVG', 'bat_OPS', 'bat_HR', 'bat_SB', 'bat_RBI',
#                         'pit_ERA', 'pit_W', 'pit_SO', 'pit_WHIP', 'pit_IP']
#         for c in numeric_cols:
#             if c in df.columns:
#                 df[c] = pd.to_numeric(df[c], errors='coerce').fillna(0)
#     except Exception as e:
#         return pd.DataFrame(), {}
# 
#     commentaries = {}
#     try:
#         response = requests.get(JSON_URL)
#         if response.status_code == 200:
#             commentaries = response.json()
#         else:
#             alt_url = JSON_URL.replace("/refs/heads/main/", "/main/")
#             response = requests.get(alt_url)
#             if response.status_code == 200:
#                 commentaries = response.json()
#     except Exception as e:
#         pass
# 
#     return df, commentaries
# 
# # 雷達圖
# def create_radar_chart(player_data):
#     player_name = player_data['Name_clean']
#     is_pitcher = player_data.get('pit_IP', 0) > 0
# 
#     fig = go.Figure()
# 
#     if is_pitcher:
#         categories = ['勝投', '奪三振', '局數', '防禦率', 'WHIP']
#         real_values = [
#             player_data.get('pit_W', 0), player_data.get('pit_SO', 0), player_data.get('pit_IP', 0),
#             player_data.get('pit_ERA', 0), player_data.get('pit_WHIP', 0)
#         ]
#         plot_values = [
#             min(real_values[0] * 5, 100), min(real_values[1] * 0.5, 100), min(real_values[2] * 0.5, 100),
#             max((5 - real_values[3]) * 20, 0), max((2 - real_values[4]) * 50, 0)
#         ]
#     else:
#         categories = ['打擊率', 'OPS', '全壘打', '打點', '盜壘']
#         real_values = [
#             player_data.get('bat_AVG', 0), player_data.get('bat_OPS', 0), player_data.get('bat_HR', 0),
#             player_data.get('bat_RBI', 0), player_data.get('bat_SB', 0)
#         ]
#         plot_values = [
#             min(real_values[0] * 300, 100), min(real_values[1] * 100, 100), min(real_values[2] * 4, 100),
#             min(real_values[3] * 1, 100), min(real_values[4] * 3, 100)
#         ]
# 
#     fig.add_trace(go.Scatterpolar(
#         r=plot_values,
#         theta=categories,
#         fill='toself',
#         name=player_name,
#         line_color='#FFD700',
#         fillcolor='rgba(255, 215, 0, 0.3)',
#         hovertemplate="%{theta}: <b>%{text}</b><extra></extra>",
#         text=[f"{v:.2f}" if isinstance(v, float) else v for v in real_values]
#     ))
# 
#     fig.update_layout(
#         polar=dict(
#             radialaxis=dict(
#                 visible=True,
#                 range=[0, 100],
#                 showticklabels=True,
#                 tickfont=dict(color='rgba(255,255,255,0.7)', size=9),
#                 gridcolor='rgba(255, 255, 255, 0.2)',
#                 linecolor='rgba(255, 255, 255, 0.2)'
#             ),
#             angularaxis=dict(
#                 visible=True,
#                 tickfont=dict(color='#FFD700', size=14, weight='bold'),
#                 gridcolor='rgba(255, 255, 255, 0.2)'
#             ),
#             bgcolor='rgba(0,0,0,0)'
#         ),
#         showlegend=False,
#         height=300,
#         margin=dict(t=40, b=20, l=40, r=40),
#         paper_bgcolor='rgba(0,0,0,0)',
#         plot_bgcolor='rgba(0,0,0,0)',
#         font=dict(color='white')
#     )
#     return fig
# 
# # 佈局
# st.title("🃏球員介紹卡牌")
# 
# st.markdown("""
# <style>
# div[data-testid="stVerticalBlockBorderWrapper"] {
#     background: linear-gradient(145deg, #1e1e2f, #2a2a40);
#     border: 2px solid #FFD700 !important;
#     border-radius: 15px;
#     box-shadow: 0 8px 16px rgba(0,0,0,0.3);
# }
# div[data-testid="stVerticalBlockBorderWrapper"] * {
#     color: white !important;
# }
# .stTabs [data-baseweb="tab-list"] { background-color: transparent; }
# .stTabs [aria-selected="true"] { color: #FFD700 !important; font-weight: bold; }
# </style>
# """, unsafe_allow_html=True)
# 
# df, commentaries = load_data()
# 
# if df.empty:
#     st.error("⚠️ 無法讀取資料")
#     st.stop()
# 
# df_players = df[df['Name_clean'].isin(TARGET_PLAYERS)].copy()
# df_players = df_players.sort_values('Year', ascending=False).drop_duplicates(subset='Name_clean', keep='first')
# 
# st.divider()
# 
# cols = st.columns(2) + st.columns(2)
# 
# count = 0
# for i, player_name in enumerate(TARGET_PLAYERS):
#     if i >= 4: break
# 
#     col = cols[i]
#     rows = df_players[df_players['Name_clean'] == player_name]
# 
#     if rows.empty:
#         col.warning(f"缺失 {player_name}")
#         continue
# 
#     data = rows.iloc[0]
#     comment = commentaries.get(player_name,)
#     fig = create_radar_chart(data)
#     photo = PLAYER_PHOTOS.get(player_name, "")
# 
#     # 判斷身分
#     role = "投手" if data.get('pit_IP', 0) > 0 else "打擊手"
# 
#     # 判斷隊名
#     team_name = data.get('Team Name_x')
#     if pd.isna(team_name) or str(team_name).lower() == 'nan':
#         team_name = TEAM_FIX.get(player_name, "CPBL")
# 
#     with col:
#         with st.container(height=600, border=True):
#             st.subheader(player_name)
#             st.caption(f"{team_name} | {role}")
# 
#             t1, t2 = st.tabs(["📷 照片", "📊 分析"])
# 
#             with t1:
#                 if photo: st.image(photo, use_container_width=True)
#                 else: st.info("無照片")
# 
#             with t2:
#                 st.markdown("#### 🧐 AI 球評")
#                 st.info(comment)
#                 st.markdown("#### 𖣠 能力雷達")
#                 st.plotly_chart(fig, use_container_width=True, config={'displayModeBar': False})
#     count += 1
# 
# if count == 0:
#     st.warning("沒有顯示任何卡牌")

"""### 互動介面"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pages/6_👾_棒球小互動.py
# import time
# from io import BytesIO
# 
# import requests
# import streamlit as st
# from PIL import Image
# from streamlit_image_coordinates import streamlit_image_coordinates
# 
# st.set_page_config(page_title="小互動", page_icon="👾", layout="wide")
# 
# BASE_URL = "https://raw.githubusercontent.com/ChewyChloe/cpbl-project/main/game"
# 
# ASSET_VER = "2025-12-24-1"
# 
# def v(url: str) -> str:
#     return f"{url}?v={ASSET_VER}"
# 
# IMAGES = {
#     "BG": v(f"{BASE_URL}/playground.png"),
#     "P": v(f"{BASE_URL}/P.png"),
#     "C": v(f"{BASE_URL}/C.png"),
#     "1B": v(f"{BASE_URL}/1B.png"),
#     "2B": v(f"{BASE_URL}/2B.png"),
#     "3B": v(f"{BASE_URL}/3B.png"),
#     "SS": v(f"{BASE_URL}/SS.png"),
#     "LF": v(f"{BASE_URL}/LF.png"),
#     "CF": v(f"{BASE_URL}/CF.png"),
#     "RF": v(f"{BASE_URL}/RF.png"),
#     "Batter": v(f"{BASE_URL}/batter.png"),
# }
# 
# players_data = {
#     "P": {"name": "王牌投手", "desc": "我是球場上的獨裁者，掌控比賽節奏！"},
#     "C": {"name": "鐵壁捕手", "desc": "我是場上的指揮官，想得分先過我這關！"},
#     "1B": {"name": "一壘大砲", "desc": "不管是接球還是打擊，我都是最穩定的存在。"},
#     "2B": {"name": "靈活二壘", "desc": "雙殺守備是我的拿手好戲，誰都別想穿越中線！"},
#     "3B": {"name": "熱角三壘", "desc": "強襲球來吧！我的反應神經可是全隊最快的。"},
#     "SS": {"name": "遊擊手", "desc": "內野防守核心，守備範圍無極限！"},
#     "LF": {"name": "左外野手", "desc": "這球飛得好遠...但我一定接得到！"},
#     "CF": {"name": "中外野手", "desc": "我是外野的隊長，這片草地由我守護。"},
#     "RF": {"name": "右外野手", "desc": "想跑三壘？小心我的長傳狙擊！"},
#     "Batter": {"name": "打擊者", "desc": "我的工作只有一個：把那顆小白球轟出場外！"},
# }
# 
# FIELD_W = 800
# FIELD_H = 600
# 
# # 位置
# PLACEMENTS = {
#     "P": {"top": 0.57, "left": 0.40, "w": 135, "h": 135},
#     "C": {"top": 0.80, "left": 0.42, "w": 120, "h": 120},
#     "Batter": {"top": 0.70, "left": 0.37, "w": 135, "h": 135},
#     "1B": {"top": 0.55, "left": 0.63, "w": 135, "h": 135},
#     "2B": {"top": 0.38, "left": 0.52, "w": 110, "h": 110},
#     "3B": {"top": 0.58, "left": 0.22, "w": 135, "h": 135},
#     "SS": {"top": 0.40, "left": 0.32, "w": 80, "h": 80},
#     "LF": {"top": 0.28, "left": 0.15, "w": 135, "h": 135},
#     "CF": {"top": 0.18, "left": 0.40, "w": 135, "h": 135},
#     "RF": {"top": 0.32, "left": 0.70, "w": 135, "h": 135},
# }
# 
# # 對話框）
# st.markdown("""
# <style>
# @import url('https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap');
# 
# .stApp {
#     font-family: 'Courier New', monospace;
#     background-color: #202020;
# }
# 
# .rpg-box-container {
#     background-color: #000080;
#     border: 6px solid #ffffff;
#     padding: 5px;
#     box-shadow: 5px 5px 0px #000000;
#     margin-top: 16px;
# }
# .rpg-box-inner {
#     background-color: #000080;
#     border: 4px solid #000080;
#     padding: 18px;
#     color: white;
#     font-family: 'Press Start 2P', cursive !important;
#     line-height: 1.8;
#     font-size: 16px;
#     min-height: 120px;
# }
# .char-name-tag {
#     font-family: 'Press Start 2P', cursive !important;
#     background-color: #e0c050;
#     color: #000000;
#     padding: 5px 15px;
#     border: 3px solid #ffffff;
#     display: inline-block;
#     margin-bottom: -10px;
#     margin-left: 10px;
#     box-shadow: 3px 3px 0px #000000;
# }
# </style>
# """, unsafe_allow_html=True)
# 
# # 點擊判定
# @st.cache_data(show_spinner=False)
# def fetch_image(url: str, ver: str) -> Image.Image:
#     r = requests.get(url, timeout=20)
#     r.raise_for_status()
#     return Image.open(BytesIO(r.content)).convert("RGBA")
# 
# def build_map(selected_role: str | None):
#     bg = fetch_image(IMAGES["BG"], ASSET_VER).resize((FIELD_W, FIELD_H))
#     regions = {}
# 
#     for role, p in PLACEMENTS.items():
#         scale = 1.3 if role == selected_role else 1.0
#         w = int(p["w"] * scale)
#         h = int(p["h"] * scale)
# 
#         sprite = fetch_image(IMAGES[role], ASSET_VER).resize((w, h))
# 
#         x = int(p["left"] * FIELD_W)
#         y = int(p["top"] * FIELD_H)
# 
#         bg.alpha_composite(sprite, (x, y))
#         regions[role] = (x, y, x + w, y + h)
# 
#     return bg, regions
# 
# def detect_role(x: int, y: int, regions: dict) -> str | None:
#     for role, (x1, y1, x2, y2) in regions.items():
#         if x1 <= x <= x2 and y1 <= y <= y2:
#             return role
#     return None
# 
# # 狀態
# if "selected_role" not in st.session_state:
#     st.session_state.selected_role = None
# if "last_click" not in st.session_state:
#     st.session_state.last_click = None
# if "last_typed_role" not in st.session_state:
#     st.session_state.last_typed_role = None
# 
# st.title("👾 像素棒球場")
# 
# left, right = st.columns([2.2, 1.0], vertical_alignment="top")
# 
# with left:
#     field_img, regions = build_map(st.session_state.selected_role)
#     clicked = streamlit_image_coordinates(field_img, width=FIELD_W)
# 
#     if clicked and "x" in clicked and "y" in clicked:
#         xy = (int(clicked["x"]), int(clicked["y"]))
#         if xy != st.session_state.last_click:
#             st.session_state.last_click = xy
#             st.session_state.selected_role = detect_role(xy[0], xy[1], regions)
#             if st.session_state.selected_role != st.session_state.last_typed_role:
#                 st.session_state.last_typed_role = None
# 
# with right:
#     role = st.session_state.selected_role
# 
#     if role:
#         data = players_data[role]
# 
#         st.image(IMAGES[role], width=180)
# 
#         st.markdown(f'<div class="char-name-tag">{data["name"]}</div>', unsafe_allow_html=True)
#         box = st.empty()
# 
#         if st.session_state.last_typed_role != role:
#             st.session_state.last_typed_role = role
#             text = ""
#             for ch in data["desc"]:
#                 text += ch
#                 box.markdown(f"""
#                 <div class="rpg-box-container">
#                     <div class="rpg-box-inner">{text}</div>
#                 </div>
#                 """, unsafe_allow_html=True)
#                 time.sleep(0.04)
#         else:
#             box.markdown(f"""
#             <div class="rpg-box-container">
#                 <div class="rpg-box-inner">{data["desc"]}</div>
#             </div>
#             """, unsafe_allow_html=True)
#     else:
#         st.markdown("""
#         <div class="rpg-box-container">
#             <div class="rpg-box-inner">
#                 （點擊球場上的球員，他們就會回應你。）
#             </div>
#         </div>
#         """, unsafe_allow_html=True)

"""### 開發團隊"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile pages/7_👥_開發團隊.py
# import streamlit as st
# from shared.styles import apply_global_style
# 
# apply_global_style()
# 
# st.header("👥 開發團隊")
# st.markdown("---")
# 
# team_members = [{"id": "113403001", "dept": "資管二", "name": "呂沛珍"}]
# 
# cols = st.columns(4)
# for i, member in enumerate(team_members):
#     with cols[i % 4]:
#         st.markdown(f"""
#         <div class="team-card">
#             <div class="team-name">{member['name']}</div>
#             <div class="team-info">{member['dept']}</div>
#             <div class="team-info">{member['id']}</div>
#         </div>
#         """, unsafe_allow_html=True)

"""### 網址"""

ngrok.kill()
my_token = userdata.get('AUTHTOKEN')
ngrok.set_auth_token(my_token)

get_ipython().system_raw('nohup streamlit run 首頁.py --server.port 80 --server.enableCORS false > output.log 2>&1 &')

public_url = ngrok.connect(80)

print(f"Streamlit App URL: {public_url}")
